-- Criação da tabela funcionarios
CREATE TABLE funcionarios (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

-- Criação da tabela animais
CREATE TABLE animal (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nome_provisorio VARCHAR(255) NOT NULL,
  idade_estimada INT NOT NULL,
  raca VARCHAR(255) NOT NULL,
  data_entrada DATE NOT NULL,
  data_adocao DATE,
  condicoes_chegada VARCHAR(255) NOT NULL,
  nome_recebedor VARCHAR(255) NOT NULL,
  data_obito DATE,
  porte VARCHAR(255) NOT NULL,
  especie VARCHAR(255) NOT NULL,
  funcionario_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id)
);
